BOARD_TAG = attiny85at8
ALTERNATE_CORE = tiny
F_CPU = 1000000L
#http://disq.us/p/1tjysc0
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/tiny/cores/tiny

RESET_CMD = :
HACKIOT_MAKEFILE = ./Makefile
AVRDUDE_ARD_BAUDRATE = 19200
AVRDUDE_ARD_PROGRAMMER = linuxspi
#AVRDUDE = /usr/bin/avrdude
ARDUINO_PORT = /dev/spidev0.1
#ARDUINO_LIBS =
USER_LIB_PATH = /workspace/libraries
#ARDUINO_DIR = /usr/share/arduino
ARDUINO_SKETCHBOOK = /usr/share/arduino
include /usr/share/arduino/Arduino_hackiot.mk