BOARD_TAG = pro5v328
RESET_CMD = :
HACKIOT_MAKEFILE = ./Makefile
AVRDUDE_ARD_PROGRAMMER = linuxspi
AVRDUDE = /usr/bin/avrdude-hackiot
ARDUINO_PORT = /dev/spidev0.1
ARDUINO_LIBS =
USER_LIB_PATH = /workspace/libraries
ARDUINO_DIR = /usr/share/arduino
include /usr/share/arduino/Arduino_hackiot.mk